"""new atributes for Treino

Revision ID: 53b51cad163b
Revises: e4aca54331af
Create Date: 2024-06-10 12:22:36.729877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b51cad163b'
down_revision = 'e4aca54331af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presenca',
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('treino_id', 'aluno_id')
    )
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorrente', sa.Boolean(), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('recorrente')

    op.drop_table('presenca')
    # ### end Alembic commands ###
