"""add time column to treino

Revision ID: e4aca54331af
Revises: 
Create Date: 2024-06-10 12:01:39.952669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4aca54331af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenca')
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('nivel', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.drop_column('nivel')
        batch_op.drop_column('horario')

    op.create_table('presenca',
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('treino_id', sa.INTEGER(), nullable=False),
    sa.Column('presente', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treino.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'treino_id')
    )
    # ### end Alembic commands ###
